apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-gitops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-gitops-app
  template:
    metadata:
      labels:
        app: my-gitops-app
    spec:
      containers:
      - name: myapp
        image: debjyoti08/nodejs-app
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-gitops-app-service
spec:
  selector:
    app: my-gitops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000